POST http://localhost:3004/todos/
Content-Type:"application/json"

{
  "id":20,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO
}
###
GET http://localhost:3001/todos/

###
PUT http://localhost:3001/todos/13/
Content-Type:"application/json"

{
  "status":DONE
}